// <auto-generated />
using System;
using BMW.CloudAdoption.BOM.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMW.CloudAdoption.BOM.Migrations
{
    [DbContext(typeof(BomContext))]
    [Migration("20220715063902_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bom")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.Bom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("bill_of_materials", "bom");
                });

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.BomPartFamily", b =>
                {
                    b.Property<int>("BomId")
                        .HasColumnType("int");

                    b.Property<int>("PartFamilyId")
                        .HasColumnType("int");

                    b.HasKey("BomId", "PartFamilyId");

                    b.HasIndex("PartFamilyId");

                    b.ToTable("bom_part_family", "bom");
                });

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.PartFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("part_families", "bom");
                });

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.PartId", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PartFamilyId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id", "PartFamilyId");

                    b.HasIndex("PartFamilyId");

                    b.ToTable("part_ids", "bom");
                });

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.BomPartFamily", b =>
                {
                    b.HasOne("BMW.CloudAdoption.BOM.Domain.Entities.Bom", "Bom")
                        .WithMany("BomPartFamilies")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMW.CloudAdoption.BOM.Domain.Entities.PartFamily", "PartFamily")
                        .WithMany("BomPartFamilies")
                        .HasForeignKey("PartFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("PartFamily");
                });

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.PartId", b =>
                {
                    b.HasOne("BMW.CloudAdoption.BOM.Domain.Entities.PartFamily", "PartFamily")
                        .WithMany("PartIds")
                        .HasForeignKey("PartFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartFamily");
                });

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.Bom", b =>
                {
                    b.Navigation("BomPartFamilies");
                });

            modelBuilder.Entity("BMW.CloudAdoption.BOM.Domain.Entities.PartFamily", b =>
                {
                    b.Navigation("BomPartFamilies");

                    b.Navigation("PartIds");
                });
#pragma warning restore 612, 618
        }
    }
}
