apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          class: private
          bootstrap:
            host: kafka-bootstrap.ttd-blue.azure.bmw.cloud
          brokers:
            - broker: 0
              host: kafka-broker-0.ttd-blue.azure.bmw.cloud
            - broker: 1
              host: kafka-broker-1.ttd-blue.azure.bmw.cloud
            - broker: 2
              host: kafka-broker-2.ttd-blue.azure.bmw.cloud
    authorization:
      type: simple
      superUsers:
        - kafka-user
        - CN=kafka-user
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}