apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    app.name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ default "ClusterIP" .Values.serviceType }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Chart.Name }}
