apiVersion: v1
kind: Secret
metadata:
  name: dev-ops-token
  namespace: {{ .Values.argocdNamespace }}
type: Opaque
data:
  username: {{ .Values.gitCredentials.username | b64enc }}
  password: {{ .Values.gitCredentials.password | b64enc }}