apiVersion: v1
kind: Secret
metadata:
  name: sops-service-principal
  namespace: {{ .Values.argocdNamespace }}
type: Opaque
data:
  tenantId: {{ .Values.sopsServicePrincipal.tenantId | b64enc }}
  clientId: {{ .Values.sopsServicePrincipal.clientId | b64enc }}
  clientSecret: {{ .Values.sopsServicePrincipal.clientSecret | b64enc }}