apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/scheme: HTTP
        prometheus.io/path: /metrics
        metrics.dynatrace.com/path: /metrics
        metrics.dynatrace.com/port: "8082"
        metrics.dynatrace.com/scheme: HTTP
        metrics.dynatrace.com/scrape: "true"