apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: "--enable_alpha_plugins"
  repositories: |
    - url: https://dev.azure.com/FG-Z-TTD-Blue/FG-Z-TTD-Blue/_git/bmw.cloudadoption.gitops
  repository.credentials: |
    - url: https://dev.azure.com/FG-Z-TTD-Blue/FG-Z-TTD-Blue/_git/bmw.cloudadoption.gitops
      passwordSecret:
        name: dev-ops-token
        key: password
      usernameSecret:
        name: dev-ops-token
        key: username
