apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.name: {{ .Chart.Name }}
data:
  {{- range $key, $value :=  .Values.environmentVariables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
