replicas: 2
revisionHistoryLimit: 5
metricsPath: /
servicePort: 8080
serviceScheme: HTTP
deploymentStrategy: RollingUpdate
terminationGracePeriodSeconds: 30
ingress:
  enabled: true
  path: /
autoscaling:
  enabled: false
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
livenessProbe:
  path: /q/health/live
readinessProbe:
  path: /q/health/ready
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
environmentVariables:
  QUARKUS_HTTP_CORS: true
  QUARKUS_HTTP_CORS_ORIGINS: "https://parts-service-ui.ttd-blue.azure.bmw.cloud,http://localhost:4200"
  KAFKA_BOOTSTRAP_SERVER: pkc-lq8gm.westeurope.azure.confluent.cloud:9092

environmentSecrets:
  KAFKA_KEY:
    secret_name: kafka-key
  KAFKA_SECRET:
    secret_name: kafka-secret
image:
  tag: dce14b8
  url: dweuttdblueacr.azurecr.io/bmw.cloudadoption.parts-java
