replicas: 1
revisionHistoryLimit: 5
metricsPath: /
servicePort: 8000
serviceScheme: HTTP
deploymentStrategy: RollingUpdate
terminationGracePeriodSeconds: 30
ingress:
  enabled: true
  path: /
autoscaling:
  enabled: false
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
livenessProbe:
  path: /
readinessProbe:
  path: /
resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 250Mi
environmentVariables:

  KAFKA_BOOTSTRAP_SERVER: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  KAFKA_PROTOCOL: SASL_PLAINTEXT
  KAFKA_SASL_MECHANISM: SCRAM-SHA-512

  KAFKA_PART_TOPIC: bmw.cloudadoption.parts.v1
  KAFKA_BOM_TOPIC: bmw.CloudAdoption.bom.python

  DB_NAME: bom_python_development_emea
  DB_HOST: dweuttdbluemssql.database.windows.net
  DB_PORT: 1433

environmentSecrets:
  KAFKA_KEY:
    secret_name: kafka-username
  KAFKA_SECRET:
    secret_name: kafka-password
  DB_USER:
    secret_name: mssql-admin
  DB_PASSWORD:
    secret_name: mssql-pw
  DB_ADMIN_USER:
    secret_name: mssql-admin
  DB_ADMIN_PASSWORD:
    secret_name: mssql-pw
image:
  tag: "20220825.6"
  url: dweuttdblueacr.azurecr.io/bmw.cloudadoption.bom-python
