apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.name: {{ .Chart.Name }}
data:
  {{- range $key, $value :=  .Values.environmentVariables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  KAFKA_CREDS_STRING: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_KEY}' password='${KAFKA_SECRET}';
  kafka.bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVER}
  kafka.security.protocol: SASL_SSL
  kafka.sasl.mechanism: PLAIN
  kafka.sasl.jaas.config: ${KAFKA_CREDS_STRING}
  quarkus.kafka-streams.application-id: bmw.CloudAdoption.{{ $.Chart.Name }}
  acks: all # Best practice for Kafka producer to prevent data loss
