version: "3.3"

services:
  # bomservice:
  #   image: dweuttdblueacr.azurecr.io/bmw.cloudadoption.bom-c:${TAG}
  #   build:
  #     context: ./BMW.CloudAdoption.BOM
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9001:80"
  #   depends_on:
  #     - kafka
  #     - sql
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNALCLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9094,EXTERNALCLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://kafka:9094,EXTERNALCLIENT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CFG_TLS_CLIENT_AUTH=none
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Passw0rd!1"
      - "MSSQL_PID=Express"
        
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
