{{- if or ($.Values.deployed) (eq ($.Values.deployed | toString) "<nil>") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.project.name }}-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.project.name }}
  source:
    repoURL: {{ $.Values.source.gitRepo }}
    targetRevision:  {{ $.Values.source.gitRevision }}
    path: resources/secrets/{{ $.Values.environment }}
  destination:
    namespace: {{ $.Values.argocd.namespace}}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
