replicas: 1
revisionHistoryLimit: 5
metricsPath: /
servicePort: 8080
serviceScheme: HTTP
deploymentStrategy: RollingUpdate
terminationGracePeriodSeconds: 30
ingress:
  enabled: true
  path: /
autoscaling:
  enabled: false
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
livenessProbe:
  path: /q/health/live
readinessProbe:
  path: /q/health/ready
resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 250Mi
environmentVariables:
  QUARKUS_HTTP_CORS: true
  QUARKUS_HTTP_CORS_ORIGINS: https://call-off-service-ui.ttd-blue.azure.bmw.cloud,http://localhost:4200
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:sqlserver://dweucloudadpmssql.database.windows.net:1433;database=calloff_java_development_emea;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  KAFKA_BOOTSTRAP_SERVER: pkc-lq8gm.westeurope.azure.confluent.cloud:9092
  kafka.bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVER}
  kafka.security.protocol: SASL_SSL
  kafka.sasl.mechanism: PLAIN
  KAFKA_CREDS_STRING: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_KEY}' password='${KAFKA_SECRET}';
  kafka.sasl.jaas.config: ${KAFKA_CREDS_STRING}
  mp.messaging.connector.smallrye-kafka.sasl.jaas.config: ${KAFKA_CREDS_STRING}
  mp.messaging.outgoing.call-offs.kafka.bootstrap.servers: pkc-lq8gm.westeurope.azure.confluent.cloud:9092
  mp.messaging.outgoing.vehicle-orders-inbound.kafka.bootstrap.servers: pkc-lq8gm.westeurope.azure.confluent.cloud:9092
  mp.messaging.outgoing.kafka-empty.kafka.bootstrap.servers: pkc-lq8gm.westeurope.azure.confluent.cloud:9092
environmentSecrets:
  KAFKA_KEY:
    secret_name: kafka-key
  KAFKA_SECRET:
    secret_name: kafka-secret
  QUARKUS_DATASOURCE_USERNAME:
    secret_name: mssql-admin
  QUARKUS_DATASOURCE_PASSWORD:
    secret_name: mssql-pw
image:
  tag: 1.0.0-SNAPSHOT-051b43f
  url: dweuttdblueacr.azurecr.io/bmw.cloudadoption.calloff
