apiVersion: v1
kind: Secret
metadata:
    name: cloud-adoption-secrets
    namespace: cloud-adoption-dev
type: Opaque
data:
    acr-server: ENC[AES256_GCM,data:O9QKHiSLcxDpl3jzAox/dCaBtJeMAEuZuynFwx2tpGJI1Slr,iv:657g7CJZ3BuSZmgbfEFCutDbebm+EwOWLlbBiDp3pSQ=,tag:xnO9lgDuIkQghGA+tSDGmg==,type:str]
    aks-pull-secret-password: ENC[AES256_GCM,data:Sfbfirbm4xaJ6x5KoDMfZMnEEnYtiPEx+iB5vU0rgknrOozj6UYyfBEyowk=,iv:IBPWyaHnBR/vMwHwp3PZpEQl0X7p8B8+pFOe1eVgpgs=,tag:KqGf/VNUu+1QQUsaBLN36w==,type:str]
    aks-pull-secret-username: ENC[AES256_GCM,data:qCbg1/8yyVRtwr8dQy8WAM437cU=,iv:vVOVZTB4oXpYLfXSJUuAQHiBR8qzAW7I50/gIJHMVIo=,tag:/nv8awCwkJpUHSRHJg7a9Q==,type:str]
    aks-pull-token: ENC[AES256_GCM,data:05phwiinpaz+ZtlxlkOlKe1Fa+k8LyUIuzSt2PnatuUyQceM4T6Ug2j3fxc=,iv:O4SHjvgF7QKdVdlOYzla4M/aU+pz+gcjSRIFwPqj2VQ=,tag:FsUKQclJOGg252xa4lJnrg==,type:str]
    application-insights-instrumentation-key: ENC[AES256_GCM,data:cNNPntjoXHURWJWGMnTU9kJ4MMVsKLMwtTEfgqHkEvTduyTTNjktpd36VtRXGtzS,iv:zQrDh3MwhO7BqRdipje0VRbemJ0/ufHvHJ/HU2M5wuU=,tag:24ngmA9wrFiKLNMbYS8QTA==,type:str]
    kafka-key: ENC[AES256_GCM,data:SiTefFFxu6nlLC0PCg5VHg==,iv:2UevZ+W7rPFDjEBiztjJWMHwl+hPs0to+TYNBUSGFZQ=,tag:2eFfKwz/Qjmbr5Qvx0P4vA==,type:str]
    kafka-password: ENC[AES256_GCM,data:Ot/No0owIkXb6LD6kK3X0A==,iv:GZIknUuf4OOUZ6xy5U1lpNUDLkzgeYNYXhLRv3VQjFs=,tag:pTWCZ+P3jyRUl+2T7jb8CQ==,type:str]
    kafka-secret: ENC[AES256_GCM,data:l6zNiSBXu1i+w5pteNZekQ==,iv:+mU7b3THaweuxaZTXxhzEaMNrfiyt3F4c9zw/WxqrJo=,tag:ujQMdpbp3P0G0xRve9F2HA==,type:str]
    kafka-username: ENC[AES256_GCM,data:MnnphQg2gJsmshS9Qa3hlQ==,iv:j60/6Z4ny0UJEdPiFqJwf23BPn6zDhNtVjBtUwjq1FE=,tag:jC3KP3dCwUMxkRwLWA0qlA==,type:str]
    mssql-admin: ENC[AES256_GCM,data:EyTdKLessf3qhZogV8rmfXJyJBSxpf9OX8hckA==,iv:hymYFVrCkUw785vensRuWrAuJmTc7ETyRlcvPzlThHo=,tag:86vxvj3obmW3yLIRnrA17w==,type:str]
    mssql-pw: ENC[AES256_GCM,data:RlsRDRv1T+gHkQoE8ozvSEH3H7VI2WagzgigBuCDBl2VycBd,iv:DDMkQ0NzHLQcAR21kcnAbq0OoII5HC9zhvMFrMZc9Zo=,tag:c4xjtZq4g61O6zl1Fs7XnQ==,type:str]
    pipeline-token: ENC[AES256_GCM,data:6vlhGP8ZgdHyXOlj1Tzyl5rFjNQKQloBJXfhrDxHlx9chDs44qQ2c7uNqr0=,iv:ezdZxw46rDZ+6X/TJ9hO4g0e2FWKdujVRskwpGUBu5w=,tag:FHIijkQd+b+DcrKArkn93Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://dweuttdbluekv.vault.azure.net
          name: sops-key
          version: a944954c39ff4076822acb91160a8d0f
          created_at: "2022-08-25T14:20:13Z"
          enc: rCCJrYSuIuUh_nFLx9HzLPFNfLK6gi06h74HV58lO0QBSrwRUFRc9ah9r1HnTYLEdbVO9uBnFHwZKwSb8pUZ5Yjs-q_gnbu-np4QG78eliCL6MPz0noTZmsuD22am8L8HOH_LlmzBMi02P4fkPcQAzZk2ue3qNI5Qbmm5XjITNwYyAbKwr1LAF-S3-QYi2K1cc1f21ts5Ec7LeJmjjHqzsApkK3Id31aru1zFJcaS4PxN0iKSYokWymJX9Y_CGN2f9bQn0kP0Tg14nzVk1Y0j6DmgVEhjQOwuMnQJAATzZZELvkzhdb941h6EaS-HdE-XIX1o_fmAavuSX8Gw0mkMw
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T14:20:13Z"
    mac: ENC[AES256_GCM,data:6z7FvRPi2YBrvjyLpYxC1mBRbpcJtEW3F9kQu2Q33V/M6JC/8q6JdH7/8+J2o42AZF1G5qIf+pTTNuwoXPvIGTdTE24wsvnz59SrodhY0BFrtmoU5dY8fkPSvs+Z8PBFh3FmpTaUXWU5Ep5ShLUw0M95p/KaLVenwqvZ1j9iTFY=,iv:OSIJljRXqoMdtcnvBxeSrWIfT/vOrN9p6kM5ssO7ew8=,tag:pnkWCqrc7Kjs1f74yXAcxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
