{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.name: {{ .Chart.Name }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value :=  .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: private
  tls:
    - hosts:
        - {{ printf "%s.ttd-blue.azure.bmw.cloud" .Chart.Name }}
      secretName: ingress-secret
  rules:
    - host: {{ printf "%s.ttd-blue.azure.bmw.cloud" .Chart.Name }}
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
          - path: /java/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.urls.java }}
                port:
                  number: 80
          - path: /csharp/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.urls.csharp }}
                port:
                  number: 80
          - path: /python/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.urls.python }}
                port:
                  number: 80
  {{- end }}
